name: kalyan_movie_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.6 
  dio: 4.0.0
  get_storage: any
  connectivity: any
  flutter_svg: any
  flare_flutter: any
  http: any
  fluttertoast: any
  shimmer: 1.1.2
  cached_network_image: ^2.3.3

  


  # rxdart: ^0.23.1
  # http: ^0.12.0+4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/animation/
    - assets/images/
    - assets/images/home/
    # - assets/icons/
    - assets/icons/
  uses-material-design: true
